### PR TITLE
Allow overriding clone depth

### PR DESCRIPTION
**Pull request by dvorak**
This changes the default for packages to be unlimited depth, but allows setting
the depth on a per project basis.  Without this change it's not possible to use
a gitref other than 'master'.

### CODE REVIEW

**Comment by dvorak** [comment]
This takes care of #17 for package build.  I've not used the docker builder, so I'm not sure what the right fix there would be.

**Comment by blueboxjesse** [comment]
Thanks for submitting these. @craigtracey is out on vacation but will review upon return!

**Comment by dvorak** [comment]
Thanks for the reply.  I'm sure I would have been wondering by the time he got back :)

**Comment by dvorak** [comment]
This is failing now because a new version of PEP8 was released on Friday.

**Comment by dvorak** [comment]
PEP8 1.6.x fixes in PR #24

**Comment by craigtracey** [comment]
I like making this configurable. The place where this makes the most sense is in Docker builds.  Why dont' we take this change, make the Docker default to depth=1 but overrideable via this change,  and for package builds do the opposite: no depth params unless specified.

**Comment by craigtracey** [comment]
@dvorak can you rebase this?

**Comment by craigtracey** [comment]
Merged after rebase.

**Pull request closed without merging**
